(function(){'use strict';var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))break a;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(h||"")+"_"+d++,h)}function c(h,f){this.g=h;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");r(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}});return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}var da=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.N=b.prototype}function w(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function la(a){return ma(a,a)}
function ma(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function na(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.o=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}na.prototype.m=function(a){this.i=a};function pa(a,b){a.j={S:b,U:!0};a.g=a.o}na.prototype.return=function(a){this.j={return:a};this.g=this.o};function x(a,b,c){a.g=c;return{value:b}}function qa(a){this.g=new na;this.h=a}
function ra(a,b){oa(a.g);var c=a.g.h;if(c)return sa(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.g.return);a.g.return(b);return y(a)}function sa(a,b,c,e){try{var d=b.call(a.g.h,c);if(!(d instanceof Object))throw new TypeError("Iterator result "+d+" is not an object");if(!d.done)return a.g.l=!1,d;var h=d.value}catch(f){return a.g.h=null,pa(a.g,f),y(a)}a.g.h=null;e.call(a.g,h);return y(a)}
function y(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,pa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.U)throw b.S;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=y(a));return b};this.throw=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h["throw"],b,a.g.m):(pa(a.g,b),b=y(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,d){function h(f){f.done?e(f.value):Promise.resolve(f.value).then(b,c).then(h,d)}h(a.next())})}
function z(a){return ua(new ta(new qa(a)))}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}u("globalThis",function(a){return a||t});
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.o=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function e(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var d=t.setTimeout;c.prototype.i=function(f){d(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(m){return function(l){k||(k=!0,m.call(g,l))}}var g=this,k=!1;return{resolve:f(this.C),reject:f(this.l)}};b.prototype.C=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.F(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.B(f):this.m(f)}};
b.prototype.B=function(f){var g=void 0;try{g=f.then}catch(k){this.l(k);return}typeof g=="function"?this.I(g,f):this.m(f)};b.prototype.l=function(f){this.v(2,f)};b.prototype.m=function(f){this.v(1,f)};b.prototype.v=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.i=g;this.h===2&&this.D();this.H()};b.prototype.D=function(){var f=this;d(function(){if(f.A()){var g=t.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.A=
function(){if(this.o)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.H=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;b.prototype.F=
function(f){var g=this.j();f.J(g.resolve,g.reject)};b.prototype.I=function(f,g){var k=this.j();try{f.call(g,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(f,g){function k(q,v){return typeof q=="function"?function(H){try{m(q(H))}catch(C){l(C)}}:v}var m,l,n=new b(function(q,v){m=q;l=v});this.J(k(f,m),k(g,l));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.J=function(f,g){function k(){switch(m.h){case 1:f(m.i);break;case 2:g(m.i);break;default:throw Error("Unexpected state: "+
m.h);}}var m=this;this.g==null?h.h(k):this.g.push(k);this.o=!0};b.resolve=e;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var m=w(f),l=m.next();!l.done;l=m.next())e(l.value).J(g,k)})};b.all=function(f){var g=w(f),k=g.next();return k.done?e([]):new b(function(m,l){function n(H){return function(C){q[H]=C;v--;v==0&&m(q)}}var q=[],v=0;do q.push(void 0),v++,e(k.value).J(n(q.length-1),l),k=g.next();while(!k.done)})};return b});
function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}u("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var e=this;e instanceof String&&(e=String(e));for(var d=e.length,h=0;h<d;h++){var f=e[h];if(b.call(c,f,h,e)){b=f;break a}}b=void 0}return b}});
u("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=w(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function e(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function d(k){if(!A(k,f)){var m=new c;r(k,f,{value:m})}}function h(k){var m=Object[k];m&&(Object[k]=function(l){if(l instanceof c)return l;Object.isExtensible(l)&&d(l);return m(l)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
l=new a([[k,2],[m,3]]);if(l.get(k)!=2||l.get(m)!=3)return!1;l.delete(k);l.set(m,4);return!l.has(k)&&l.get(m)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,m){if(!e(k))throw Error("Invalid WeakMap key");d(k);if(!A(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=m;return this};b.prototype.get=function(k){return e(k)&&A(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return e(k)&&A(k,
f)&&A(k[f],this.g)};b.prototype.delete=function(k){return e(k)&&A(k,f)&&A(k[f],this.g)?delete k[f][this.g]:!1};return b});
u("Map",function(a){function b(){var g={};return g.u=g.next=g.head=g}function c(g,k){var m=g[1];return ca(function(){if(m){for(;m.head!=g[1];)m=m.u;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function e(g,k){var m=k&&typeof k;m=="object"||m=="function"?h.has(k)?m=h.get(k):(m=""+ ++f,h.set(k,m)):m="p_"+k;var l=g[0][m];if(l&&A(g[0],m))for(g=0;g<l.length;g++){var n=l[g];if(k!==k&&n.key!==n.key||k===n.key)return{id:m,list:l,index:g,entry:n}}return{id:m,
list:l,index:-1,entry:void 0}}function d(g){this[0]={};this[1]=b();this.size=0;if(g){g=w(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(w([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),l=m.next();if(l.done||l.value[0]!=g||l.value[1]!="s")return!1;l=m.next();return l.done||l.value[0].x!=
4||l.value[1]!="t"||!m.next().done?!1:!0}catch(n){return!1}}())return a;var h=new WeakMap;d.prototype.set=function(g,k){g=g===0?0:g;var m=e(this,g);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],u:this[1].u,head:this[1],key:g,value:k},m.list.push(m.entry),this[1].u.next=m.entry,this[1].u=m.entry,this.size++);return this};d.prototype.delete=function(g){g=e(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.u.next=g.entry.next,
g.entry.next.u=g.entry.u,g.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].u=b();this.size=0};d.prototype.has=function(g){return!!e(this,g).entry};d.prototype.get=function(g){return(g=e(this,g).entry)&&g.value};d.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};d.prototype.keys=function(){return c(this,function(g){return g.key})};d.prototype.values=function(){return c(this,function(g){return g.value})};d.prototype.forEach=
function(g,k){for(var m=this.entries(),l;!(l=m.next()).done;)l=l.value,g.call(k,l[1],l[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var f=0;return d});u("Array.from",function(a){return a?a:function(b,c,e){c=c!=null?c:function(g){return g};var d=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)d.push(c.call(e,h.value,f++))}else for(h=b.length,f=0;f<h;f++)d.push(c.call(e,b[f],f));return d}});
u("Object.entries",function(a){return a?a:function(b){var c=[],e;for(e in b)A(b,e)&&c.push([e,b[e]]);return c}});u("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});u("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});u("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});u("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});
u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});u("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var d=e.length;c=c||0;for(c<0&&(c=Math.max(c+d,0));c<d;c++){var h=e[c];if(h===b||Object.is(h,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});
function wa(a,b){a instanceof String&&(a+="");var c=0,e=!1,d={next:function(){if(!e&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}e=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d}u("Array.prototype.entries",function(a){return a?a:function(){return wa(this,function(b,c){return[b,c]})}});u("Object.values",function(a){return a?a:function(b){var c=[],e;for(e in b)A(b,e)&&c.push(b[e]);return c}});
u("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});u("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});u("Array.prototype.values",function(a){return a?a:function(){return wa(this,function(b,c){return c})}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var xa=xa||{},B=this||self;function ya(a,b){a=a.split(".");b=b||B;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function za(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function Aa(a){var b=za(a);return b=="array"||b=="object"&&typeof a.length=="number"}function D(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function Ba(a,b,c){return a.call.apply(a.bind,arguments)}
function Ca(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function Da(a,b,c){Da=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Ba:Ca;return Da.apply(null,arguments)}
function Ea(a,b){function c(){}c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.la=function(e,d,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[d].apply(e,f)}};var Fa;function Ga(a){B.setTimeout(function(){throw a;},0)};var Ha,Ia=ya("CLOSURE_FLAGS"),Ja=Ia&&Ia[748402147];Ha=Ja!=null?Ja:!0;function Ka(){var a=B.navigator;return a&&(a=a.userAgent)?a:""};var La=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,e=typeof a==="string"?a.split(""):a,d=0;d<c;d++)d in e&&b.call(void 0,e[d],d,a)};
function Na(a,b){b=La(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Oa(a){var b=a.length;if(b>0){for(var c=Array(b),e=0;e<b;e++)c[e]=a[e];return c}return[]};var Pa=Ka().toLowerCase().indexOf("webkit")!=-1&&Ka().indexOf("Edge")==-1&&Ka().indexOf("Mobile")!=-1;var Qa=typeof B.BigInt==="function"&&typeof B.BigInt(0)==="bigint";var Ra=Number.MIN_SAFE_INTEGER.toString(),Sa=Qa?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ta=Number.MAX_SAFE_INTEGER.toString(),Ua=Qa?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Va(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var e=a[c],d=b[c];if(e>d)return!1;if(e<d)return!0}};var Wa=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Xa(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Ya=Xa("jas",void 0,!0),Za=Xa(void 0,"0actk"),E=Xa("m_m","ma",!0);var $a=Math.max,ab=$a.apply,bb=Object.values({ea:1,da:2,ca:4,ia:8,ka:16,ga:32,X:64,aa:128,Y:256,ja:512,Z:1024,ba:2048,ha:4096,fa:8192}),cb;if(bb instanceof Array)cb=bb;else{for(var db=w(bb),eb,fb=[];!(eb=db.next()).done;)fb.push(eb.value);cb=fb}ab.call($a,Math,cb);var gb={T:{value:0,configurable:!0,writable:!0,enumerable:!1}},hb=Object.defineProperties,F=Wa?Ya:"T";function ib(a,b){Wa||F in a||hb(a,gb);a[F]|=b}function G(a,b){Wa||F in a||hb(a,gb);a[F]=b};var I={};function J(a,b){return b===void 0?a.h!==K&&!!(2&(a.g[F]|0)):!!(2&b)&&a.h!==K}var K={};var jb=void 0;function kb(a){return a.displayName||a.name||"unknown type name"};function lb(a){return a};function mb(a,b,c,e){var d=e!==void 0;e=!!e;var h=[],f=a.length,g=4294967295,k=!1,m=!!(b&64),l=m?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,g=f):n=void 0;if(m&&!(b&128)&&!d){k=!0;var q;g=((q=nb)!=null?q:lb)(g-l,l,a,n,void 0)+l}}b=void 0;for(d=0;d<f;d++)if(q=a[d],q!=null&&(q=c(q,e))!=null)if(m&&d>=g){var v=d-l,H=void 0;((H=b)!=null?H:b={})[v]=q}else h[d]=q;if(n)for(var C in n)a=n[C],a!=null&&(a=c(a,e))!=null&&(f=+C,d=void 0,m&&!Number.isNaN(f)&&
(d=f+l)<g?h[d]=a:(f=void 0,((f=b)!=null?f:b={})[C]=a));b&&(k?h.push(b):h[g]=b);return h}function ob(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Qa?a>=Sa&&a<=Ua:a[0]==="-"?Va(a,Ra):Va(a,Ta))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[F]|0;return a.length===0&&b&1?void 0:mb(a,b,ob)}if(a!=null&&a[E]===I)return pb(a);return}return a}var nb;function pb(a){a=a.g;return mb(a,a[F]|0,ob)};function qb(a,b,c){var e=e===void 0?0:e;if(a==null){var d=32;c?(a=[c],d|=128):a=[];b&&(d=d&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");d=a[F]|0;if(Ha&&1&d)throw Error("rfarr");2048&d&&!(2&d)&&rb();if(d&256)throw Error("farr");if(d&64)return e!==0||d&2048||G(a,d|2048),a;if(c&&(d|=128,c!==a[0]))throw Error("mid");a:{c=a;d|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=d&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=
+k,h<f&&(c[h+b]=g[k],delete g[k]);d=d&-16760833|(f&1023)<<14;break a}}if(b){k=Math.max(b,h-(d&128?0:-1));if(k>1024)throw Error("spvt");d=d&-16760833|(k&1023)<<14}}}d|=64;e===0&&(d|=2048);G(a,d);return a}function rb(){if(Ha)throw Error("carr");if(Za!=null){var a;var b=(a=jb)!=null?a:jb={};a=b[Za]||0;a>=5||(b[Za]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",Ga(b))}};function sb(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[F]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=L(a,c,!1,b&&!(c&16)):(ib(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[E]===I)return b=a.g,c=b[F]|0,J(a,c)?a:tb(a,b,c)?ub(a,b):L(b,c)}function ub(a,b,c){a=new a.constructor(b);c&&(a.h=K);a.i=K;return a}function L(a,b,c,e){e!=null||(e=!!(34&b));a=mb(a,b,sb,e);e=32;c&&(e|=2);b=b&16769217|e;G(a,b);return a}
function vb(a){if(a.h!==K)return!1;var b=a.g;b=L(b,b[F]|0);ib(b,2048);a.g=b;a.h=void 0;a.i=void 0;return!0}function wb(a){if(!vb(a)&&J(a,a.g[F]|0))throw Error();}function xb(a,b){b===void 0&&(b=a[F]|0);b&32&&!(b&4096)&&G(a,b|4096)}function tb(a,b,c){return c&2?!0:c&32&&!(c&4096)?(G(b,c|2),a.h=K,!0):!1};function yb(a,b,c){if(b===-1)return null;var e=b+-1,d=a.length-1;if(!(d<0)){if(e>=d){var h=a[d];if(h!=null&&typeof h==="object"&&h.constructor===Object){d=h[b];var f=!0}else if(e===d)d=h;else return}else d=a[e];if(c&&d!=null){c=c(d);if(c==null)return c;if(!Object.is(c,d))return f?h[b]=c:a[e]=c,c}return d}}
function zb(a,b,c,e){var d=c+-1,h=a.length-1;if(h>=0&&d>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=e,b}if(d<=h)return a[d]=e,b;if(e!==void 0){var g;h=((g=b)!=null?g:b=a[F]|0)>>14&1023||536870912;c>=h?e!=null&&(d={},a[h+-1]=(d[c]=e,d)):a[d]=e}return b}
function Ab(a,b){var c=M,e=!1,d=yb(a,1,function(h){if(h!=null&&h[E]===I)var f=h;else if(Array.isArray(h)){f=h[F]|0;var g=f|b&32;g|=b&2;g!==f&&G(h,g);f=new c(h)}else f=void 0;e=f!==h&&f!=null;return f});if(d!=null)return e&&!J(d)&&xb(a,b),d}function Bb(a){var b=a.g,c=b[F]|0,e=Ab(b,c);if(e==null)return e;c=b[F]|0;if(!J(a,c)){var d=e;var h=d.g,f=h[F]|0;d=J(d,f)?tb(d,h,f)?ub(d,h,!0):new d.constructor(L(h,f,!1)):d;d!==e&&(vb(a)&&(b=a.g,c=b[F]|0),e=d,c=zb(b,c,1,e),xb(b,c))}return e}
function N(a,b){var c=c===void 0?!1:c;Object.isExtensible(a);a=yb(a.g,b);a=a!==null?a:void 0;a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}function O(a,b,c){if(c!=null&&typeof c!=="boolean")throw Error("Expected boolean but got "+za(c)+": "+c);wb(a);var e=a.g;zb(e,e[F]|0,b,c===!1?void 0:c);return a};function P(a,b,c){this.g=qb(a,b,c)}P.prototype.toJSON=function(){var a=pb(this);return a};P.prototype[E]=I;P.prototype.toString=function(){return this.g.toString()};var Cb=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function Q(){this.l=this.l;this.o=this.o}Q.prototype.l=!1;Q.prototype.isDisposed=function(){return this.l};Q.prototype.dispose=function(){this.l||(this.l=!0,this.G())};Q.prototype[Symbol.dispose]=function(){this.dispose()};Q.prototype.G=function(){if(this.o)for(;this.o.length;)this.o.shift()()};var Db="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Eb(a,b){for(var c,e,d=1;d<arguments.length;d++){e=arguments[d];for(c in e)a[c]=e[c];for(var h=0;h<Db.length;h++)c=Db[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Fb=globalThis.trustedTypes,Gb;function Hb(){var a=null;if(!Fb)return a;try{var b=function(c){return c};a=Fb.createPolicy("uf-api#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function Ib(a){this.g=a}Ib.prototype.toString=function(){return this.g+""};function Jb(a){var b;Gb===void 0&&(Gb=Hb());a=(b=Gb)?b.createScriptURL(a):a;return new Ib(a)};var Kb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Lb(a,b){b=Kb.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)}function Mb(a){a=a===void 0?document:a;var b,c;a=(c=(b=a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};function Nb(a,b){if(b instanceof Ib)b=b.g;else throw Error("");a.src=b;(b=Mb(a.ownerDocument))&&a.setAttribute("nonce",b)};function Ob(a){var b=va.apply(1,arguments);if(b.length===0)return Jb(a[0]);for(var c=a[0],e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return Jb(c)};function Pb(a,b,c){function e(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var d=1;d<c.length;d++){var h=c[d];if(!Aa(h)||D(h)&&h.nodeType>0)e(h);else{a:{if(h&&typeof h.length=="number"){if(D(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}Ma(f?Oa(h):h,e)}}}function Qb(a){var b="SCRIPT";a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function Rb(a){this.g=a||B.document||document}Rb.prototype.append=function(a,b){Pb(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments)};function Sb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var Tb="closure_listenable_"+(Math.random()*1E6|0);var Ub=0;function Vb(a,b,c,e,d){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!e;this.M=d;this.key=++Ub;this.K=this.L=!1}function R(a){a.K=!0;a.listener=null;a.proxy=null;a.src=null;a.M=null};function Wb(a){this.src=a;this.g={};this.h=0}Wb.prototype.add=function(a,b,c,e,d){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var f=Xb(a,b,e,d);f>-1?(b=a[f],c||(b.L=!1)):(b=new Vb(b,this.src,h,!!e,d),b.L=c,a.push(b));return b};function Yb(a,b){var c=b.type;c in a.g&&Na(a.g[c],b)&&(R(b),a.g[c].length==0&&(delete a.g[c],a.h--))}function Xb(a,b,c,e){for(var d=0;d<a.length;++d){var h=a[d];if(!h.K&&h.listener==b&&h.capture==!!c&&h.M==e)return d}return-1};var Zb="closure_lm_"+(Math.random()*1E6|0),$b={},ac=0;
function bc(a,b,c,e,d){if(Array.isArray(b))for(var h=0;h<b.length;h++)bc(a,b[h],c,e,d);else(e=D(e)?!!e.capture:!!e,c=cc(c),a&&a[Tb])?(a=a.i,b=String(b).toString(),b in a.g&&(h=a.g[b],c=Xb(h,c,e,d),c>-1&&(R(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.g[b],a.h--)))):a&&(a=dc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Xb(b,c,e,d)),(c=a>-1?b[a]:null)&&typeof c!=="number"&&c&&!c.K&&((d=c.src)&&d[Tb]?Yb(d.i,c):(e=c.type,b=c.proxy,d.removeEventListener?d.removeEventListener(e,b,c.capture):
d.detachEvent?d.detachEvent(e in $b?$b[e]:$b[e]="on"+e,b):d.addListener&&d.removeListener&&d.removeListener(b),ac--,(e=dc(d))?(Yb(e,c),e.h==0&&(e.src=null,d[Zb]=null)):R(c))))}function dc(a){a=a[Zb];return a instanceof Wb?a:null}var ec="__closure_events_fn_"+(Math.random()*1E9>>>0);function cc(a){if(typeof a==="function")return a;a[ec]||(a[ec]=function(b){return a.handleEvent(b)});return a[ec]};function S(){Q.call(this);this.i=new Wb(this);this.P=this;this.C=null}Ea(S,Q);S.prototype[Tb]=!0;S.prototype.removeEventListener=function(a,b,c,e){bc(this,a,b,c,e)};
function T(a,b){var c=a.C;if(c){var e=[];for(var d=1;c;c=c.C)e.push(c),++d}a=a.P;c=b.type||b;typeof b==="string"?b=new Sb(b,a):b instanceof Sb?b.target=b.target||a:(d=b,b=new Sb(c,a),Eb(b,d));d=!0;var h;if(e)for(h=e.length-1;h>=0;h--){var f=b.g=e[h];d=U(f,c,!0,b)&&d}f=b.g=a;d=U(f,c,!0,b)&&d;d=U(f,c,!1,b)&&d;if(e)for(h=0;h<e.length;h++)f=b.g=e[h],d=U(f,c,!1,b)&&d}
S.prototype.G=function(){S.N.G.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var e=a.g[c],d=0;d<e.length;d++)++b,R(e[d]);delete a.g[c];a.h--}}this.C=null};function U(a,b,c,e){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var d=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.K&&f.capture==c){var g=f.listener,k=f.M||f.src;f.L&&Yb(a.i,f);d=g.call(k,e)!==!1&&d}}return d&&!e.defaultPrevented};function fc(a){try{return B.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var hc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function V(){S.call(this);this.headers=new Map;this.h=!1;this.g=null;this.B="";this.j=this.A=this.m=this.H=!1;this.D=0;this.v=null;this.I="";this.F=!1}Ea(V,S);var ic=/^https?$/i,jc=["POST","PUT"],kc=[];function lc(a,b){var c=new V;kc.push(c);b&&c.i.add("complete",b,!1,void 0,void 0);c.i.add("ready",c.R,!0,void 0,void 0);c.D=2E3;c.F=!0;mc(c,a)}p=V.prototype;p.R=function(){this.dispose();Na(kc,this)};
function mc(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.B+"; newUri="+b);a.B=b;a.H=!1;a.h=!0;a.g=new XMLHttpRequest;a.g.onreadystatechange=Cb(Da(a.O,a));try{a.A=!0,a.g.open("GET",String(b),!0),a.A=!1}catch(h){nc(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var e in c)b.set(e,c[e]);else if(typeof c.keys==="function"&&typeof c.get==="function"){e=w(c.keys());for(var d=e.next();!d.done;d=e.next())d=d.value,b.set(d,
c.get(d))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(h){return"content-type"==h.toLowerCase()});e=B.FormData&&!1;!(La(jc,"GET")>=0)||c||e||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=w(b);for(c=b.next();!c.done;c=b.next())e=w(c.value),c=e.next().value,e=e.next().value,a.g.setRequestHeader(c,e);a.I&&(a.g.responseType=a.I);"withCredentials"in a.g&&a.g.withCredentials!==a.F&&(a.g.withCredentials=a.F);try{oc(a),
a.D>0&&(a.v=setTimeout(a.W.bind(a),a.D)),a.m=!0,a.g.send(""),a.m=!1}catch(h){nc(a)}}p.W=function(){typeof xa!="undefined"&&this.g&&(T(this,"timeout"),this.abort(8))};function nc(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);pc(a);qc(a)}function pc(a){a.H||(a.H=!0,T(a,"complete"),T(a,"error"))}p.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,T(this,"complete"),T(this,"abort"),qc(this))};
p.G=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),qc(this,!0));V.N.G.call(this)};p.O=function(){this.isDisposed()||(this.A||this.m||this.j?rc(this):this.V())};p.V=function(){rc(this)};
function rc(a){if(a.h&&typeof xa!="undefined")if(a.m&&(a.g?a.g.readyState:0)==4)setTimeout(a.O.bind(a),0);else if(T(a,"readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{try{var b=(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(f){b=-1}a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var e;if(!(e=c)){var d;if(d=b===0){var h=String(a.B).match(hc)[1]||null;!h&&B.self&&B.self.location&&(h=B.self.location.protocol.slice(0,-1));d=!ic.test(h?h.toLowerCase():
"")}e=d}e?(T(a,"complete"),T(a,"success")):pc(a)}finally{qc(a)}}}function qc(a,b){if(a.g){oc(a);var c=a.g;a.g=null;b||T(a,"ready");try{c.onreadystatechange=null}catch(e){}}}function oc(a){a.v&&(clearTimeout(a.v),a.v=null)}p.isActive=function(){return!!this.g};function M(a){this.g=qb(a)}ka(M,P);p=M.prototype;p.getEnableSsEngine=function(){return N(this,2)};p.getEnableAwr=function(){return N(this,3)};p.getAlohaAutoGaRollout=function(){return N(this,5)};p.getEnableConfigurator=function(){return N(this,6)};p.getEnableMweb=function(){return N(this,7)};p.getEnableCtlConsentCheckbox=function(){return N(this,8)};p.getEnableIframe=function(){return N(this,9)};p.getEnableScreenshotNudge=function(){return N(this,10)};
p.getEnableWebStartupConfigEndpoint=function(){return N(this,11)};p.getEnableJunkNudge=function(){return N(this,12)};p.getEnableConfiguratorLocale=function(){return N(this,13)};p.getEnableTinyNoPointer=function(){return N(this,14)};p.getEnableSupportSessionLogging=function(){return N(this,15)};p.getEnableFileUploadForScreenshot=function(){return N(this,16)};p.getEnableDirectDeflectionForSingleCategory=function(){return N(this,17)};p.getEnableImageSanitization=function(){return N(this,18)};
p.getEnableAlohaBinarySplit=function(){return N(this,19)};p.getEnableDbFeedbackIntents=function(){return N(this,20)};p.getEnableMarkMandatoryFieldsWithRequired=function(){return N(this,21)};p.getEnableFeedbackCategoryCustomUi=function(){return N(this,22)};p.getEnableRealtimeCtl=function(){return N(this,23)};function sc(a){this.g=qb(a)}ka(sc,P);function tc(a){return uc.some(function(b){return b.test(a)})}var uc=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var vc="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");var wc=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),xc=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
function yc(a,b){var c;var e=(c=a.formContent)==null?void 0:c.locale;c=e==null?void 0:e.split("-")[0];e=e&&vc.includes(e)?e:c&&vc.includes(c)?c:void 0;e=(e!=null?e:"en").replaceAll("-","_").toLowerCase();var d;a=((d=a.initializationData)==null?0:d.useNightlyRelease)?"nightly":"live";var h;return(b==null?0:(h=b.getEnableAlohaBinarySplit)==null?0:h.call(b))?Ob(wc,a):Ob(xc,a,e)};function W(){var a=Error.call(this,"Form is either loading or already opened");this.message=a.message;"stack"in a&&(this.stack=a.stack);this.name="DuplicateFormError"}ka(W,Error);var zc,Ac,Bc,Cc;
function Dc(a,b,c,e){if(zc&&Bc===b)return zc;Bc=b;var d=yc(a,e);return zc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Qb(document);Nb(g,d);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+d.toString()))};c.body.appendChild(g)})}
function Ec(a,b,c,e){if(Ac&&Cc===b)return Ac;Cc=b;var d=yc(a,e);return Ac=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Qb(document);Nb(g,d);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+d.toString()))};c.body.appendChild(g)})}
function Fc(a,b,c,e,d){d=d===void 0?!0:d;var h,f,g,k,m;return z(function(l){switch(l.g){case 1:return h=Date.now(),x(l,Dc(a,c,e,b),2);case 2:f=l.i;if(!(d||((k=a.initializationData)==null?0:k.useNightlyRelease)||((m=a.initializationData)==null?0:m.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);l.g=3;break}return x(l,f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=l.i;case 3:return g.initiateAloha(),l.return(g)}})}
function Gc(a,b,c,e){var d,h,f;return z(function(g){if(g.g==1)return d=Date.now(),x(g,Ec(a,c,e.document,b),2);if(g.g!=3)return h=g.i,x(g,h.initializeFeedbackClientAsync(a,d,b,e),3);f=g.i;f.initiateAloha();return g.return(f)})}
function Hc(a,b,c){var e=!0;e=e===void 0?!0:e;var d,h,f,g,k,m,l,n;return z(function(q){d=c||B;if((h=b)==null?0:(g=(f=h).getEnableAlohaBinarySplit)==null?0:g.call(f)){k=d;if(k.isFormOpened)throw new W;k.isFormOpened=!0;a.callbacks=a.callbacks||{};m=a.callbacks.onClose||function(){};a.callbacks.onClose=function(v){k.isFormOpened=!1;m(v)};try{return q.return(Gc(a,b,k,d))}catch(v){throw k.isFormOpened=!1,v;}}else{l=d;if(l.isFormOpened)throw new W;l.isFormOpened=!0;a.callbacks=a.callbacks||{};n=a.callbacks.onClose||
function(){};a.callbacks.onClose=function(v){l.isFormOpened=!1;n(v)};try{return q.return(Fc(a,b,l,d.document,e))}catch(v){throw l.isFormOpened=!1,v;}}q.g=0})};function Ic(a,b){return z(function(c){return c.return(new Promise(function(e,d){Number.isInteger(Number(a))&&Number(a)>0?(d=Jc(b!=null?b:"")+"/aloha_form_properties?productId="+a,lc(d,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.g){var m=f.g.responseText;m.indexOf(")]}'\n")==0&&(m=m.substring(5));b:{if(B.JSON)try{var l=B.JSON.parse(m);break b}catch(v){}l=fc(m)}}else l=void 0;var n=k.call(g,l);if(n==null||n=="")h=new sc;else{var q=JSON.parse(n);if(!Array.isArray(q))throw Error("dnarr");
ib(q,32);h=new sc(q)}}catch(v){k=new sc;l=new M;l=O(l,5,!0);l=O(l,2,!0);l=O(l,4,!1);l=O(l,8,!0);l=O(l,9,!0);l=O(l,7,!0);l=O(l,10,!0);l=O(l,12,!0);l=O(l,13,!1);l=O(l,14,!0);l=O(l,15,!0);l=O(l,20,!1);n=M;if(l!=null){if(!(l instanceof n))throw Error("Expected instanceof "+kb(n)+" but got "+(l&&kb(l.constructor)));}else l=void 0;n=l;wb(k);q=k.g;zb(q,q[F]|0,1,n);l&&!J(l)&&xb(k.g);h=k}e(h)})):d(Error("Invalid product id: "+a))}))})}function Jc(a){return tc(a)?a:"https://www.google.com/tools/feedback"};function X(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||B,d=e.document,h=a.nonce||Mb(e.document);h&&!a.nonce&&(a.nonce=h);if(a.flow=="help"){var f=ya("document.location.href",e);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var g=JSON.stringify(b);(f=g.length<=1200)&&(a.psdJson=g)}f||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=e.GOOGLE_FEEDBACK_START)f.apply(e,
b);else{e=c+"/load.js?";for(var k in a)b=a[k],b==null||D(b)||(e+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=d?new Rb(d.nodeType==9?d:d.ownerDocument||d.document):Fa||(Fa=new Rb);a=Qb(a.g);h&&a.setAttribute("nonce",h);h=Jb(e);Nb(a,h);d.body.appendChild(a)}}
function Kc(a,b,c,e){var d,h;return z(function(f){d=c||B;var g=a.serverEnvironment==="DEV",k=c||B;k=a.nonce||Mb(k.document);g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,na:void 0,defaultFormInputValues:void 0,
defaultFormInputValuesString:void 0,abuseLink:a.abuseLink,additionalDataConsent:a.additionalDataConsent},initializationData:{isLocalServer:g,nonce:k,useNightlyRelease:g,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(k=new Map(Object.entries(b)),g.extraData.productSpecificData=k);h=g;return x(f,Hc(h,e,d),0)})}
function Lc(a,b,c){try{if(a.flow==="help"){var e=a.helpCenterPath.replace(/^\//,"");Lb(c||window,"https://support.google.com/"+e)}else a.flow==="submit"?X(a,b,c):Ic(a.productId,a.feedbackServerUri).then(function(d){d=Bb(d);var h=!Pa||(d==null?void 0:d.getEnableMweb()),f=!a.tinyNoPointer||(d==null?void 0:d.getEnableTinyNoPointer());!d||d.getAlohaAutoGaRollout()&&h&&f?Kc(a,b,c,d).catch(function(g){!g||g instanceof W||X(a,b,c)}):X(a,b,c)},function(d){!d||d instanceof W||X(a,b,c)})}catch(d){Kc(a,b,c,
null).catch(function(h){!h||h instanceof W||X(a,b,c)})}}for(var Mc=["userfeedback","api","startFeedback"],Y=B,Z;Mc.length&&(Z=Mc.shift());)Mc.length||Lc===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Lc;}).call(this);
