(function(){'use strict';var q;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function v(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}}
v("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.$jscomp$symbol$id_=h;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.$jscomp$symbol$id_};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");r(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}});return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}var da=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype}function w(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function y(a){if(!(a instanceof Array)){a=w(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function z(a){return la(a,a)}function la(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var ma=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)A(d,e)&&(a[e]=d[e])}return a};v("Object.assign",function(a){return a||ma});function na(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=0;this.abruptCompletion_=null}
function oa(a){if(a.isRunning_)throw new TypeError("Generator is already running");a.isRunning_=!0}na.prototype.JSC$2822_next_=function(a){this.yieldResult=a};function pa(a,b){a.abruptCompletion_={exception:b,isException:!0};a.nextAddress=a.finallyAddress_}na.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};function qa(a){this.context_=new na;this.program_=a}
function ra(a,b){oa(a.context_);var c=a.context_.yieldAllIterator_;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.context_.return);a.context_.return(b);return C(a)}
function sa(a,b,c,d){try{var e=b.call(a.context_.yieldAllIterator_,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.context_.isRunning_=!1,e;var h=e.value}catch(f){return a.context_.yieldAllIterator_=null,pa(a.context_,f),C(a)}a.context_.yieldAllIterator_=null;d.call(a.context_,h);return C(a)}
function C(a){for(;a.context_.nextAddress;)try{var b=a.program_(a.context_);if(b)return a.context_.isRunning_=!1,{value:b.value,done:!1}}catch(c){a.context_.yieldResult=void 0,pa(a.context_,c)}a.context_.isRunning_=!1;if(a.context_.abruptCompletion_){b=a.context_.abruptCompletion_;a.context_.abruptCompletion_=null;if(b.isException)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.context_);a.context_.yieldAllIterator_?b=sa(a,a.context_.yieldAllIterator_.next,b,a.context_.JSC$2822_next_):(a.context_.JSC$2822_next_(b),b=C(a));return b};this.throw=function(b){oa(a.context_);a.context_.yieldAllIterator_?b=sa(a,a.context_.yieldAllIterator_["throw"],b,a.context_.JSC$2822_next_):(pa(a.context_,b),b=C(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}
function ua(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}v("globalThis",function(a){return a||t});
v("Promise",function(a){function b(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.batch_=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.asyncExecute=function(f){if(this.batch_==null){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(f)};var e=t.setTimeout;
c.prototype.asyncExecuteFunction=function(f){e(f,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var g=0;g<f.length;++g){var k=f[g];f[g]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};b.prototype.createResolveAndReject_=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.resolveTo_),
reject:f(this.reject_)}};b.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(f):this.fulfill_(f)}};b.prototype.resolveToNonPromiseObj_=function(f){var g=void 0;try{g=f.then}catch(k){this.reject_(k);return}typeof g=="function"?this.settleSameAsThenable_(g,
f):this.fulfill_(f)};b.prototype.reject_=function(f){this.settle_(2,f)};b.prototype.fulfill_=function(f){this.settle_(1,f)};b.prototype.settle_=function(f,g){if(this.state_!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=g;this.state_===2&&this.scheduleUnhandledRejectionCheck_();this.executeOnSettledCallbacks_()};b.prototype.scheduleUnhandledRejectionCheck_=function(){var f=this;e(function(){if(f.notifyUnhandledRejection_()){var g=
t.console;typeof g!=="undefined"&&g.error(f.result_)}},1)};b.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.result_;return k(f)};
b.prototype.executeOnSettledCallbacks_=function(){if(this.onSettledCallbacks_!=null){for(var f=0;f<this.onSettledCallbacks_.length;++f)h.asyncExecute(this.onSettledCallbacks_[f]);this.onSettledCallbacks_=null}};var h=new c;b.prototype.settleSameAsPromise_=function(f){var g=this.createResolveAndReject_();f.callWhenSettled_(g.resolve,g.reject)};b.prototype.settleSameAsThenable_=function(f,g){var k=this.createResolveAndReject_();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=
function(f,g){function k(p,x){return typeof p=="function"?function(u){try{l(p(u))}catch(B){m(B)}}:x}var l,m,n=new b(function(p,x){l=p;m=x});this.callWhenSettled_(k(f,l),k(g,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.callWhenSettled_=function(f,g){function k(){switch(l.state_){case 1:f(l.result_);break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;this.onSettledCallbacks_==null?h.asyncExecute(k):this.onSettledCallbacks_.push(k);
this.isRejectionHandled_=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=w(f),m=l.next();!m.done;m=l.next())d(m.value).callWhenSettled_(g,k)})};b.all=function(f){var g=w(f),k=g.next();return k.done?d([]):new b(function(l,m){function n(u){return function(B){p[u]=B;x--;x==0&&l(p)}}var p=[],x=0;do p.push(void 0),x++,d(k.value).callWhenSettled_(n(p.length-1),m),k=g.next();while(!k.done)})};return b});
v("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});v("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});
v("WeakMap",function(a){function b(k){this.id_=(g+=Math.random()+1).toString();if(k){k=w(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!A(k,f)){var l=new c;r(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!A(k,f))throw Error("WeakMap key fail: "+k);k[f][this.id_]=l;return this};b.prototype.get=function(k){return d(k)&&A(k,f)?k[f][this.id_]:void 0};b.prototype.has=function(k){return d(k)&&
A(k,f)&&A(k[f],this.id_)};b.prototype.delete=function(k){return d(k)&&A(k,f)&&A(k[f],this.id_)?delete k[f][this.id_]:!1};return b});
v("Map",function(a){function b(){var g={};return g.previous=g.next=g.head=g}function c(g,k){var l=g[1];return ca(function(){if(l){for(;l.head!=g[1];)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&A(g[0],l))for(g=0;g<m.length;g++){var n=m[g];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:g,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=w(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(w([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],previous:this[1].previous,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].previous.next=l.entry,this[1].previous=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,
function(g){return g.value})};e.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});v("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push(b[d]);return c}});v("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
v("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});v("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});v("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
v("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
v("String.prototype.startsWith",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this+"";b+="";var e=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<h&&c<e;)if(d[c++]!=b[f++])return!1;return f>=h}});
function wa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}v("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});v("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});
v("Array.prototype.values",function(a){return a?a:function(){return wa(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var xa=xa||{},D=this||self;function ya(a,b){a=a.split(".");for(var c=D,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function E(a,b){a=a.split(".");b=b||D;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function za(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function Aa(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
var Ba="closure_uid_"+(Math.random()*1E9>>>0),Ca=0;function Da(a,b,c){return a.call.apply(a.bind,arguments)}function Ea(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function Fa(a,b,c){Fa=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Da:Ea;return Fa.apply(null,arguments)}function Ga(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}};var F;function Ha(a){D.setTimeout(function(){throw a;},0)};var Ia,Ja=E("CLOSURE_FLAGS"),Ka=Ja&&Ja[748402147];Ia=Ka!=null?Ka:!0;var La=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Oa(a,b){b=La(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Pa(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Qa={},G=null;
function Ra(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);e>255&&(b[c++]=e&255,e>>=8);b[c++]=e}a=2;a===void 0&&(a=0);if(!G)for(G={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;e<5;e++){var h=c.concat(d[e].split(""));Qa[e]=h;for(var f=0;f<h.length;f++){var g=h[f];G[g]===void 0&&(G[g]=f)}}a=Qa[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=h=0;h<b.length-2;h+=3){var k=b[h],l=b[h+1];g=b[h+2];f=a[k>>2];k=a[(k&3)<<
4|l>>4];l=a[(l&15)<<2|g>>6];g=a[g&63];c[e++]=""+f+k+l+g}f=0;g=d;switch(b.length-h){case 2:f=b[h+1],g=a[(f&15)<<2]||d;case 1:b=b[h],c[e]=""+a[b>>2]+a[(b&3)<<4|f>>4]+g+d}return c.join("")};var Sa=void 0;var Ta=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Ua(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Va=Ua("jas",void 0,!0),Wa=Ua(void 0,"0actk"),H=Ua("m_m","messagePrototypeMarker",!0);Math.max.apply(Math,y(Object.values({IS_REPEATED_FIELD:1,IS_IMMUTABLE_ARRAY:2,IS_API_FORMATTED:4,ONLY_MUTABLE_VALUES:8,UNFROZEN_SHARED:16,MUTABLE_REFERENCES_ARE_OWNED:32,CONSTRUCTED:64,HAS_MESSAGE_ID:128,FROZEN_ARRAY:256,STRING_FORMATTED:512,GBIGINT_FORMATTED:1024,HAS_WRAPPER:2048,MUTABLE_SUBSTRUCTURES:4096,KNOWN_MAP_ARRAY:8192})));var Xa={internalArrayState:{value:0,configurable:!0,writable:!0,enumerable:!1}},Ya=Object.defineProperties,I=Ta?Va:"internalArrayState";
function Za(a,b){Ta||I in a||Ya(a,Xa);a[I]|=b}function J(a,b){Ta||I in a||Ya(a,Xa);a[I]=b};var K={};function L(a,b){return b===void 0?a.copyOnWrite!==M&&!!(2&(a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows[I]|0)):!!(2&b)&&a.copyOnWrite!==M}var M={};var $a=typeof D.BigInt==="function"&&typeof D.BigInt(0)==="bigint";var ab=Number.MIN_SAFE_INTEGER.toString(),bb=$a?BigInt(Number.MIN_SAFE_INTEGER):void 0,cb=Number.MAX_SAFE_INTEGER.toString(),db=$a?BigInt(Number.MAX_SAFE_INTEGER):void 0;function eb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};function fb(a){return a};function gb(a,b,c,d){var e=d!==void 0;d=!!d;var h=[],f=a.length,g=4294967295,k=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,g=f):n=void 0;if(l&&!(b&128)&&!e){k=!0;var p;g=((p=hb)!=null?p:fb)(g-m,m,a,n,void 0)+m}}b=void 0;for(e=0;e<f;e++)if(p=a[e],p!=null&&(p=c(p,d))!=null)if(l&&e>=g){var x=e-m,u=void 0;((u=b)!=null?u:b={})[x]=p}else h[e]=p;if(n)for(var B in n)a=n[B],a!=null&&(a=c(a,d))!=null&&(f=+B,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<g?h[e]=a:(f=void 0,((f=b)!=null?f:b={})[B]=a));b&&(k?h.push(b):h[g]=b);return h}function ib(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return($a?a>=bb&&a<=db:a[0]==="-"?eb(a,ab):eb(a,cb))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[I]|0;return a.length===0&&b&1?void 0:gb(a,b,ib)}if(a!=null&&a[H]===K)return N(a);return}return a}var hb;
function N(a){a=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows;return gb(a,a[I]|0,ib)};function jb(a,b,c){var d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[I]|0;if(Ia&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&kb();if(e&256)throw Error("farr");if(e&64)return d!==0||e&2048||J(a,e|2048),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=
+k,h<f&&(c[h+b]=g[k],delete g[k]);e=e&-16760833|(f&1023)<<14;break a}}if(b){k=Math.max(b,h-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}e|=64;d===0&&(e|=2048);J(a,e);return a}function kb(){if(Ia)throw Error("carr");if(Wa!=null){var a;var b=(a=Sa)!=null?a:Sa={};a=b[Wa]||0;a>=5||(b[Wa]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",Ha(b))}};function lb(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[I]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=O(a,c,!1,b&&!(c&16)):(Za(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[H]===K)return b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[I]|0,L(a,c)?a:mb(a,b,c)?nb(a,b):O(b,c)}function nb(a,b,c){a=new a.constructor(b);c&&(a.copyOnWrite=M);a.noLegacyNull=M;return a}
function O(a,b,c,d){d!=null||(d=!!(34&b));a=gb(a,b,lb,d);d=32;c&&(d|=2);b=b&16769217|d;J(a,b);return a}function ob(a,b){b===void 0&&(b=a[I]|0);b&32&&!(b&4096)&&J(a,b|4096)}function mb(a,b,c){return c&2?!0:c&32&&!(c&4096)?(J(b,c|2),a.copyOnWrite=M,!0):!1};var pb={};function qb(a,b,c){Object.isExtensible(a);b=rb(a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,b);if(b!==null||c&&a.noLegacyNull!==M)return b}function rb(a,b,c){if(b===-1)return null;var d=b+-1,e=a.length-1;if(!(e<0)){if(d>=e){var h=a[e];if(h!=null&&typeof h==="object"&&h.constructor===Object){e=h[b];var f=!0}else if(d===e)e=h;else return}else e=a[d];if(c&&e!=null){c=c(e);if(c==null)return c;if(!Object.is(c,e))return f?h[b]=c:a[d]=c,c}return e}}
function sb(a,b){var c=tb,d=!1,e=rb(a,10,function(h){if(h!=null&&h[H]===K)var f=h;else if(Array.isArray(h)){f=h[I]|0;var g=f|b&32;g|=b&2;g!==f&&J(h,g);f=new c(h)}else f=void 0;d=f!==h&&f!=null;return f});if(e!=null)return d&&!L(e)&&ob(a,b),e}
function ub(a){var b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[I]|0,d=sb(b,c);if(d==null)return d;c=b[I]|0;if(!L(a,c)){var e=d;var h=e.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,f=h[I]|0;e=L(e,f)?mb(e,h,f)?nb(e,h,!0):new e.constructor(O(h,f,!1)):e;if(e!==d){a.copyOnWrite===M?(d=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,d=O(d,d[I]|0),Za(d,2048),a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=d,a.copyOnWrite=void 0,a.noLegacyNull=void 0,d=!0):d=
!1;d&&(b=a.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows,c=b[I]|0);d=e;a:{a=b;e=d;h=a.length-1;if(h>=0&&9>=h&&(f=a[h],f!=null&&typeof f==="object"&&f.constructor===Object)){f[10]=e;break a}if(9<=h)a[9]=e;else if(e!==void 0){var g;h=((g=c)!=null?g:c=a[I]|0)>>14&1023||536870912;10>=h?e!=null&&(g={},a[h+-1]=(g[10]=e,g)):a[9]=e}}ob(b,c)}}return d}function vb(a,b,c){a=qb(a,b,c);return a==null||typeof a==="string"?a:void 0}
function wb(a){var b=b===void 0?!1:b;a=qb(a,5);a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:b};function P(a,b,c){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=jb(a,b,c)}P.prototype.toJSON=function(){return N(this)};function xb(a,b){if(b==null||b=="")return new a;b=JSON.parse(b);if(!Array.isArray(b))throw Error("dnarr");Za(b,32);return new a(b)}P.prototype[H]=K;P.prototype.toString=function(){return this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows.toString()};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var yb=globalThis.trustedTypes,zb;function Ab(){var a=null;if(!yb)return a;try{var b=function(c){return c};a=yb.createPolicy("rep-api#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function Bb(a){this.privateDoNotAccessOrElseWrappedResourceUrl=a}Bb.prototype.toString=function(){return this.privateDoNotAccessOrElseWrappedResourceUrl+""};function Cb(a){var b;zb===void 0&&(zb=Ab());a=(b=zb)?b.createScriptURL(a):a;return new Bb(a)};var Fb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Q(a){var b=va.apply(1,arguments);if(b.length===0)return Cb(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Cb(c)};var Gb=z(["https://www.google.com/tools/feedback/"]),Hb=z(["http://localhost.corp.google.com/inapp/"]),Ib=z(["http://localhost.proxy.googlers.com/inapp/"]),Jb=z(["https://asx-frontend-autopush.corp.google.com/inapp/"]),Kb=z(["https://asx-frontend-autopush.corp.google.com/tools/feedback/"]),Lb=z(["https://asx-frontend-autopush.corp.google.co.uk/inapp/"]),Mb=z(["https://asx-frontend-autopush.corp.google.co.uk/tools/feedback/"]),Nb=z(["https://asx-frontend-autopush.corp.google.de/inapp/"]),Ob=z(["https://asx-frontend-autopush.corp.google.de/tools/feedback/"]),
Pb=z(["https://asx-frontend-autopush.corp.youtube.com/tools/feedback/"]),Qb=z(["https://asx-frontend-autopush.corp.youtube.com/inapp/"]),Rb=z(["https://asx-help-frontend-autopush.corp.youtube.com/tools/feedback/"]),Sb=z(["https://asx-help-frontend-autopush.corp.youtube.com/inapp/"]),Tb=z(["https://asx-frontend-staging.corp.google.com/inapp/"]),Ub=z(["https://asx-frontend-staging.corp.google.com/tools/feedback/"]),Vb=z(["https://support.google.com/inapp/"]),Wb=z(["https://sandbox.google.com/inapp/"]),
Xb=z(["https://sandbox.google.com/tools/feedback/"]),Yb=z(["https://www.google.cn/tools/feedback/"]),Zb=z(["https://help.youtube.com/tools/feedback/"]),$b=z(["https://asx-frontend-staging.corp.google.com/inapp/"]),ac=z(["https://asx-frontend-staging.corp.google.com/tools/feedback/"]),bc=z(["https://localhost.corp.google.com/inapp/"]),cc=z(["https://localhost.proxy.googlers.com/inapp/"]),dc=Q(Gb),ec=[Q(Hb),Q(Ib)],fc=[Q(Jb),Q(Kb),Q(Lb),Q(Mb),Q(Nb),Q(Ob),Q(Pb),Q(Qb),Q(Rb),Q(Sb)],hc=[Q(Tb),Q(Ub)],ic=
[dc,Q(Vb),Q(Wb),Q(Xb),Q(Yb),Q(Zb),Q($b),Q(ac),Q(bc),Q(cc)];y(ec);y(fc);y(hc);y(ic);var jc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function kc(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<jc.length;h++)c=jc[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function lc(a,b){b=Fb.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)};function mc(a,b){if(b instanceof Bb)b=b.privateDoNotAccessOrElseWrappedResourceUrl;else throw Error("");a.src=b;var c;b=a.ownerDocument;b=b===void 0?document:b;var d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,"script[nonce]");(c=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",c)};function nc(a,b,c){function d(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var h=c[e];if(!za(h)||Aa(h)&&h.nodeType>0)d(h);else{a:{if(h&&typeof h.length=="number"){if(Aa(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}Ma(f?Pa(h):h,d)}}}function oc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}
function pc(a){return a.nodeType==9?a:a.ownerDocument||a.document}function R(a){this.document_=a||D.document||document}function qc(a,b){a=a.document_;b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}R.prototype.append=function(a,b){nc(pc(a),a,arguments)};R.prototype.JSC$2989_removeNode=oc;
R.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function S(a,b){var c;try{a?c=Ra(encodeURIComponent(JSON.stringify(N(a)))):b&&(c=Ra(encodeURIComponent(b)))}catch(d){console.log("Failed to serialize and encode proto: ",d)}return c}function rc(a){if(a){var b=a.style.width;a.style.width="0";a.style.display="none";a.style.width=b!=null?b:"360px";a.replaceChildren()}else oc(document.getElementById("help_panel_main_frame"))}
function T(a){var b=va.apply(1,arguments),c=E("gapi.rpc");c&&c.setup&&c.sendHandshake&&c.call&&(c.setup(""),c.sendHandshake("help_panel_main_frame/help_panel_content_frame",""),c.call.apply(c,["help_panel_main_frame/help_panel_content_frame",a,null].concat(y(b))))};function U(){}U.prototype.reloadWithOptions=function(a){var b=S(void 0,a.startingFlowSerializedJspb),c=S(void 0,a.frdProductDataSerializedJspb);a=S(void 0,a.gseSessionOptionsSerializedJspb);T("newGseSession",c,a,b)};U.prototype.sendUiBidirCommsRequest=function(a){T("gseUiBidirCommsRequest",a.requestId,a.requestData)};U.prototype.sendUiBidirCommsResponse=function(a){T("gseUiBidirCommsResponse",a.requestId,a.responseData)};
U.prototype.updateProductData=function(a){T("gseAdaptiveContext",S(void 0,a.frdProductDataSerializedJspb),S(void 0,a.productCustomDataSerializedJspb),a.productSpecificData)};function tb(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=jb(a)}ka(tb,P);function sc(a){this.internalArrayDoNotAccessOrElseMightBeUndefinedWhoKnows=jb(a)}ka(sc,P);var tc=function(a){return function(b){return xb(a,b)}}(sc);var uc=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function V(){this.disposed_=this.disposed_;this.onDisposeCallbacks_=this.onDisposeCallbacks_}V.prototype.disposed_=!1;V.prototype.isDisposed=function(){return this.disposed_};V.prototype.dispose=function(){this.disposed_||(this.disposed_=!0,this.disposeInternal())};V.prototype[Symbol.dispose]=function(){this.dispose()};V.prototype.disposeInternal=function(){if(this.onDisposeCallbacks_)for(;this.onDisposeCallbacks_.length;)this.onDisposeCallbacks_.shift()()};function vc(a,b){this.type=a;this.JSC$3011_currentTarget=this.target=b;this.defaultPrevented=!1};var wc="closure_listenable_"+(Math.random()*1E6|0);var xc=0;function yc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.handler=e;this.key=++xc;this.removed=this.callOnce=!1}function W(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.handler=null};function zc(a){this.src=a;this.listeners={};this.typeCount_=0}zc.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.listeners[h];a||(a=this.listeners[h]=[],this.typeCount_++);var f=Ac(a,b,d,e);f>-1?(b=a[f],c||(b.callOnce=!1)):(b=new yc(b,this.src,h,!!d,e),b.callOnce=c,a.push(b));return b};function Bc(a,b){var c=b.type;c in a.listeners&&Oa(a.listeners[c],b)&&(W(b),a.listeners[c].length==0&&(delete a.listeners[c],a.typeCount_--))}
function Ac(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.removed&&h.listener==b&&h.capture==!!c&&h.handler==d)return e}return-1};var Cc="closure_lm_"+(Math.random()*1E6|0),Dc={},Ec=0;
function Fc(a,b,c,d,e){if(Array.isArray(b))for(var h=0;h<b.length;h++)Fc(a,b[h],c,d,e);else(d=Aa(d)?!!d.capture:!!d,c=Gc(c),a&&a[wc])?(a=a.eventTargetListeners_,b=String(b).toString(),b in a.listeners&&(h=a.listeners[b],c=Ac(h,c,d,e),c>-1&&(W(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.listeners[b],a.typeCount_--)))):a&&(a=Hc(a))&&(b=a.listeners[b.toString()],a=-1,b&&(a=Ac(b,c,d,e)),(c=a>-1?b[a]:null)&&typeof c!=="number"&&c&&!c.removed&&((e=c.src)&&e[wc]?Bc(e.eventTargetListeners_,
c):(d=c.type,b=c.proxy,e.removeEventListener?e.removeEventListener(d,b,c.capture):e.detachEvent?e.detachEvent(d in Dc?Dc[d]:Dc[d]="on"+d,b):e.addListener&&e.removeListener&&e.removeListener(b),Ec--,(d=Hc(e))?(Bc(d,c),d.typeCount_==0&&(d.src=null,e[Cc]=null)):W(c))))}function Hc(a){a=a[Cc];return a instanceof zc?a:null}var Ic="__closure_events_fn_"+(Math.random()*1E9>>>0);function Gc(a){if(typeof a==="function")return a;a[Ic]||(a[Ic]=function(b){return a.handleEvent(b)});return a[Ic]};function X(){V.call(this);this.eventTargetListeners_=new zc(this);this.actualEventTarget_=this;this.parentEventTarget_=null}Ga(X,V);X.prototype[wc]=!0;X.prototype.removeEventListener=function(a,b,c,d){Fc(this,a,b,c,d)};
function Y(a,b){var c=a.parentEventTarget_;if(c){var d=[];for(var e=1;c;c=c.parentEventTarget_)d.push(c),++e}a=a.actualEventTarget_;c=b.type||b;typeof b==="string"?b=new vc(b,a):b instanceof vc?b.target=b.target||a:(e=b,b=new vc(c,a),kc(b,e));e=!0;var h;if(d)for(h=d.length-1;h>=0;h--){var f=b.JSC$3011_currentTarget=d[h];e=Jc(f,c,!0,b)&&e}f=b.JSC$3011_currentTarget=a;e=Jc(f,c,!0,b)&&e;e=Jc(f,c,!1,b)&&e;if(d)for(h=0;h<d.length;h++)f=b.JSC$3011_currentTarget=d[h],e=Jc(f,c,!1,b)&&e}
X.prototype.disposeInternal=function(){X.superClass_.disposeInternal.call(this);if(this.eventTargetListeners_){var a=this.eventTargetListeners_,b=0,c;for(c in a.listeners){for(var d=a.listeners[c],e=0;e<d.length;e++)++b,W(d[e]);delete a.listeners[c];a.typeCount_--}}this.parentEventTarget_=null};
function Jc(a,b,c,d){b=a.eventTargetListeners_.listeners[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.removed&&f.capture==c){var g=f.listener,k=f.handler||f.src;f.callOnce&&Bc(a.eventTargetListeners_,f);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function Kc(a){try{return D.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var Lc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Mc(){X.call(this);this.headers=new Map;this.active_=!1;this.xhr_=null;this.lastUri_="";this.inAbort_=this.inOpen_=this.inSend_=this.errorDispatched_=!1;this.timeoutId_=null;this.responseType_="";this.withCredentials_=!1}Ga(Mc,X);var Nc=/^https?$/i,Oc=["POST","PUT"],Pc=[];function Qc(a,b){var c=new Mc;Pc.push(c);b&&c.eventTargetListeners_.add("complete",b,!1,void 0,void 0);c.eventTargetListeners_.add("ready",c.cleanupSend_,!0,void 0,void 0);c.withCredentials_=!0;Rc(c,a)}q=Mc.prototype;
q.cleanupSend_=function(){this.dispose();Oa(Pc,this)};
function Rc(a,b){if(a.xhr_)throw Error("[goog.net.XhrIo] Object is active with another request="+a.lastUri_+"; newUri="+b);a.lastUri_=b;a.errorDispatched_=!1;a.active_=!0;a.xhr_=new XMLHttpRequest;a.xhr_.onreadystatechange=uc(Fa(a.onReadyStateChange_,a));try{a.inOpen_=!0,a.xhr_.open("GET",String(b),!0),a.inOpen_=!1}catch(e){Sc(a);return}b=new Map(a.headers);var c=Array.from(b.keys()).find(function(e){return"content-type"==e.toLowerCase()}),d=D.FormData&&!1;!(La(Oc,"GET")>=0)||c||d||b.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");b=w(b);for(c=b.next();!c.done;c=b.next())d=w(c.value),c=d.next().value,d=d.next().value,a.xhr_.setRequestHeader(c,d);a.responseType_&&(a.xhr_.responseType=a.responseType_);"withCredentials"in a.xhr_&&a.xhr_.withCredentials!==a.withCredentials_&&(a.xhr_.withCredentials=a.withCredentials_);try{Tc(a),a.inSend_=!0,a.xhr_.send(""),a.inSend_=!1}catch(e){Sc(a)}}
function Sc(a){a.active_=!1;a.xhr_&&(a.inAbort_=!0,a.xhr_.abort(),a.inAbort_=!1);Uc(a);Vc(a)}function Uc(a){a.errorDispatched_||(a.errorDispatched_=!0,Y(a,"complete"),Y(a,"error"))}q.abort=function(){this.xhr_&&this.active_&&(this.active_=!1,this.inAbort_=!0,this.xhr_.abort(),this.inAbort_=!1,Y(this,"complete"),Y(this,"abort"),Vc(this))};q.disposeInternal=function(){this.xhr_&&(this.active_&&(this.active_=!1,this.inAbort_=!0,this.xhr_.abort(),this.inAbort_=!1),Vc(this,!0));Mc.superClass_.disposeInternal.call(this)};
q.onReadyStateChange_=function(){if(!this.isDisposed())if(this.inOpen_||this.inSend_||this.inAbort_)Wc(this);else this.onReadyStateChangeEntryPoint_()};q.onReadyStateChangeEntryPoint_=function(){Wc(this)};
function Wc(a){if(a.active_&&typeof xa!="undefined")if(a.inSend_&&(a.xhr_?a.xhr_.readyState:0)==4)setTimeout(a.onReadyStateChange_.bind(a),0);else if(Y(a,"readystatechange"),(a.xhr_?a.xhr_.readyState:0)==4){a.active_=!1;try{try{var b=(a.xhr_?a.xhr_.readyState:0)>2?a.xhr_.status:-1}catch(f){b=-1}a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var h=String(a.lastUri_).match(Lc)[1]||null;!h&&D.self&&D.self.location&&
(h=D.self.location.protocol.slice(0,-1));e=!Nc.test(h?h.toLowerCase():"")}d=e}d?(Y(a,"complete"),Y(a,"success")):Uc(a)}finally{Vc(a)}}}function Vc(a,b){if(a.xhr_){Tc(a);var c=a.xhr_;a.xhr_=null;b||Y(a,"ready");try{c.onreadystatechange=null}catch(d){}}}function Tc(a){a.timeoutId_&&(clearTimeout(a.timeoutId_),a.timeoutId_=null)}q.isActive=function(){return!!this.xhr_};function Xc(a){if(!a)return null;a=vb(a,4,pb);var b;a===null||a===void 0?b=null:b=Cb(a);return b};var Yc=z([""]),Zc=z(["https://www.google.com/tools/feedback/help_panel_binary.js"]);
function $c(a,b,c,d,e,h){return ua(new ta(new qa(function(f){return f.return(new Promise(function(g){Qc(""+a+"/repeater_help_panel?locale="+b+"&helpContext="+c+"&productId="+d+"&helpcenter="+e+"&openingMode="+h,function(k){var l=k.target;k=null;try{var m=JSON,n=m.stringify;if(l.xhr_){var p=l.xhr_.responseText;p.indexOf(")]}'\n")==0&&(p=p.substring(5));b:{if(D.JSON)try{var x=D.JSON.parse(p);break b}catch(u){}x=Kc(p)}}else x=void 0;k=xb(sc,n.call(m,x))}catch(u){}g(k)})}))})))}
function ad(a,b,c,d){var e=a.helpCenterPath.startsWith("/")?a.helpCenterPath.substring(1):a.helpCenterPath,h=tc(b),f=a.helpPanelMode||0,g=a.fixedHelpPanelContainer,k=a.customHelpPanelContainer;g&&f!==1?g=void 0:f!==1||g&&!wb(h)||(f=0,g=void 0);k&&f!==2?f=2:f!==2||k&&!a.anchor||(f=0,k=void 0);var l=a.minimizeMode;f!==2||l&&l!==0?f===1&&(l=2):l=2;var m=a.openingMode;if(a.directToGetHelp)m=2;else if(a.supportContentUrl||a.defaultHelpArticleId)m=3;var n=c.document,p=a.nonce,x=ub(h)?Xc(ub(h))||Q(Yc):Q(Zc),
u=E("document.location.href",c);a.helpCenterContext||a.context||!u||(a.context=u.substring(0,1200));u=!0;if(d){var B=JSON.stringify(d);(u=B.length<=1200)&&(a.psdJson=B)}u||(d={invalidPsd:!0});var Db=a.helpPanelTheme;a.helpPanelTheme===2&&(Db=c.matchMedia&&c.matchMedia("(prefers-color-scheme: dark)").matches?1:0);u=qc(n?new R(pc(n)):F||(F=new R),"SCRIPT");p&&u.setAttribute("nonce",p);u.onload=function(){var id=c.startHelpPanel,jd=a.channel,kd=a.context||a.helpCenterContext||c.location.href,ld=a.defaultHelpArticleFragment,
md=a.defaultHelpArticleId,nd=a.defaultHelpArticleHelpcenterPath,od=a.directToGetHelp||!1,pd=a.openToHelpGuideEntryButtonId,qd=a.enableHelpGuideMaximize,rd=a.enableHelpGuideConversationalAi,sd=a.enableHelpGuideHumanChat;var Na=Na===void 0?"":Na;var Eb;var td=(Eb=vb(h,12))!=null?Eb:Na;id.call(c,{helpcenter:e,apiKey:"testpage",channel:jd,context:kd,defaultHelpArticleFragment:ld,defaultHelpArticleId:md,defaultHelpArticleHelpcenterPath:nd,directToGetHelp:od,openToHelpGuideEntryButtonId:pd,enableHelpGuideMaximize:qd,
enableHelpGuideConversationalAi:rd,enableHelpGuideHumanChat:sd,internalHelpCenter:td,enableSendFeedback:a.enableSendFeedback||!1,helpPanelTheme:Db,locale:a.locale,nd4cSettingsIsEnabled:a.nd4cSettingsIsEnabled||!1,nd4cSettingsCountryCode:a.nd4cSettingsCountryCode||"",serverData:b,supportContentUrl:a.supportContentUrl,symptom:a.symptom,helpApiData:{helpApiConfig:a,frdProductData:a.frdProductData,productData:d,productWindow:c},helpPanelMode:f,onPromotedProductLinkClickCallback:a.onPromotedProductLinkClickCallback,
fixedHelpPanelContainer:g,customHelpPanelContainer:k,openingMode:m,onMinimizeCallback:a.onMinimizeCallback,onGseEventCallback:a.onGseEventCallback,minimizeMode:l||0,helpFlowSessionId:a.helpFlowSessionId||a.supportVisitId,helpGuideHelpCenterEmbedEntryPoint:a.helpGuideHelpCenterEmbedEntryPoint,helpGuideCommonEmbedEntryPoint:a.helpGuideCommonEmbedEntryPoint,helpGuideStartingFlow:a.helpGuideStartingFlow,gseSessionOptions:a.gseSessionOptions,helpPanelStartTimeMs:a.helpPanelStartTimeMs,disableEndUserCredentials:a.disableEndUserCredentials,
gsePageUrl:a.gsePageUrl,mendelIds:a.mendelIds,productDeepLinkRegex:a.productDeepLinkRegex,onProductDeepLinkClickCallback:a.onProductDeepLinkClickCallback,supportJourneyId:a.supportJourneyId})};mc(u,x);n.body.appendChild(u)};function bd(a){a=a||{};return{onGseEventCallback:a.onGseEventCallback,gseSessionOptions:S(a.gseSessionOptions,a.gseSessionOptionsSerializedJspb),helpGuideUri:a.helpGuideUri,gsePageUrl:a.pageUrl,mendelIds:a.mendelIds}}
function cd(a){a=a||{};return{customHelpPanelContainer:a.customHelpPanelContainer,fixedHelpPanelContainer:a.fixedHelpPanelContainer,helpPanelMode:a.helpPanelMode,helpPanelTheme:a.helpPanelTheme,minimizeMode:a.minimizeMode,onMinimizeCallback:a.onMinimizeCallback,onRestoreCallback:a.onRestoreCallback}}function dd(a){var b=document.getElementById("help_panel_main_frame");return b&&b.style.visibility==="hidden"?(b.style.visibility="visible",a&&a(),b.focus(),!0):!1};var ed;function fd(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d="aria-"+b;c===""||c==void 0?(ed||(c={},ed=(c.atomic=!1,c.autocomplete="none",c.dropeffect="none",c.haspopup=!1,c.live="off",c.multiline=!1,c.multiselectable=!1,c.orientation="vertical",c.readonly=!1,c.relevant="additions text",c.required=!1,c.sort="none",c.busy=!1,c.disabled=!1,c.hidden=!1,c.invalid="false",c)),c=ed,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};function gd(a){V.call(this);this.domHelper_=a||F||(F=new R);this.liveRegions_={};this.lastMessageAnnouncedPerPriority_={}}Ga(gd,V);gd.prototype.disposeInternal=function(){var a=this.liveRegions_,b=this.domHelper_.JSC$2989_removeNode,c=this.domHelper_,d;for(d in a)b.call(c,a[d],d,a);this.lastMessageAnnouncedPerPriority_=this.domHelper_=this.liveRegions_=null;gd.superClass_.disposeInternal.call(this)};
function hd(a,b){var c;if(c=a.liveRegions_.assertive)c.removeAttribute("aria-hidden");else{var d=c=qc(a.domHelper_,"DIV");var e=c;e=Object.prototype.hasOwnProperty.call(e,Ba)&&e[Ba]||(e[Ba]=++Ca);d.id="goog-lr-"+e;c.style.position="absolute";c.style.top="-1000px";c.style.height="1px";c.style.overflow="hidden";fd(c,"live","assertive");fd(c,"atomic","true");a.domHelper_.document_.body.appendChild(c);a.liveRegions_.assertive=c}d=(d=a.lastMessageAnnouncedPerPriority_.assertive)&&d===b?b+"\u00a0":b;b&&
(a.lastMessageAnnouncedPerPriority_.assertive=d);if("textContent"in c)c.textContent=d;else if(c.nodeType==3)c.data=String(d);else if(c.firstChild&&c.firstChild.nodeType==3){for(;c.lastChild!=c.firstChild;)c.removeChild(c.lastChild);c.firstChild.data=String(d)}else{for(;a=c.firstChild;)c.removeChild(a);c.appendChild(pc(c).createTextNode(String(d)))}};function Z(a){this.productId=a;this.announcer=new gd}q=Z.prototype;
q.openHelp=function(a){var b=ud;var c=Object;var d=c.assign,e=vd(this,a.commonConfig),h=bd(a.commonGseConfig),f=a.nd4cSettings||{};c=d.call(c,{},e,h,cd(a.helpPanelConfig),a.feedbackConfig,{nd4cSettingsIsEnabled:f.isEnabled,nd4cSettingsCountryCode:f.countryCode},{enableSendFeedback:a.enableSendFeedback,openingMode:1,onPromotedProductLinkClickCallback:a.onPromotedProductLinkClickCallback});b(this,{topLevelConfig:c,commonConfig:a.commonConfig,helpPanelConfig:a.helpPanelConfig,openingMode:1})};
q.openToGse=function(a){var b=ud;var c=vd(this,a.commonConfig);var d=bd(a.commonGseConfig),e=cd(a.helpPanelConfig),h=a||{};c=Object.assign({},{customHelpPanelContainer:e.customHelpPanelContainer,internalHelpCenterName:h.internalHelpCenterName,helpGuideStartingFlow:S(h.startingFlow,h.startingFlowSerializedJspb),openingMode:4},c,d,e);b(this,{topLevelConfig:c,commonConfig:a.commonConfig,helpPanelConfig:a.helpPanelConfig,openingMode:4});return new U};
q.openToContent=function(a){var b=ud;var c=vd(this,a.commonConfig);var d=a||{};c=Object.assign({},{supportContentUrl:d.supportContentUrl,defaultHelpArticleId:d.defaultHelpArticleId,defaultHelpArticleFragment:d.defaultHelpArticleFragment,openingMode:3},c,cd(a.helpPanelConfig));b(this,{topLevelConfig:c,commonConfig:a.commonConfig,helpPanelConfig:a.helpPanelConfig,openingMode:3})};
q.openToSmartJourney=function(a){var b=ud;var c=vd(this,a.commonConfig);var d=a||{};c=Object.assign({},{channel:d.channel,symptom:d.symptom,openingMode:2},c,cd(a.helpPanelConfig));b(this,{topLevelConfig:c,commonConfig:a.commonConfig,helpPanelConfig:a.helpPanelConfig,openingMode:2})};
function ud(a,b){var c=b.commonConfig,d=b.helpPanelConfig,e=b.openingMode,h=b.topLevelConfig;if(!dd(d==null?void 0:d.onRestoreCallback)){c.openHelpScreenReaderAnnouncement&&hd(a.announcer,c.openHelpScreenReaderAnnouncement);b=c.locale||"en".replace(/-/g,"_");var f=c.helpCenterPath;f=f.startsWith("/")?f.substring(1):f;var g=c.asxFrontEndUri||"https://www.google.com/tools/feedback",k=c.context||"",l=c.productData,m=(d==null?void 0:d.fixedHelpPanelContainer)||void 0;a.fixedHelpPanelContainer=m;try{$c(g,
b,k,a.productId,f,e).then(function(n){rc(m);ad(h,JSON.stringify(N(n)),a.currentWindow,l)})}catch(n){lc(a.currentWindow,"https://support.google.com/"+f)}}}
function vd(a,b){b=b||{};var c=(new Date).getTime();a.currentWindow=b.window||top||window;c={anchor:b.anchor,authuser:b.authuser,context:b.context,onCloseCallback:b.onCloseCallback,onLoadCallback:b.onLoadCallback,userIpForTesting:b.userIpForTesting,helpCenterPath:b.helpCenterPath,locale:b.locale||"en".replace(/-/g,"_"),nonce:b.nonce,productData:b.productData,asxFrontEndUri:b.asxFrontEndUri,asxUiUri:b.asxUiUri,renderApiUri:b.renderApiUri,window:b.window,helpPanelStartTimeMs:c,frdProductData:S(b.frdProductData,
b.frdProductDataSerializedJspb),productId:a.productId,disableEndUserCredentials:b.disableEndUserCredentials,onProductDeepLinkClickCallback:b.onProductDeepLinkClickCallback,productDeepLinkRegex:b.productDeepLinkRegex,domain:a.currentWindow.location.protocol+"//"+a.currentWindow.location.host,serverUri:b.asxFrontEndUri,supportVisitId:b.supportVisitId,supportJourneyId:b.supportJourneyId};a.onCloseCallback=b.onCloseCallback;return c}
q.updateContext=function(a){var b=E("gapi.rpc");b&&document.getElementById("help_panel_main_frame")!==null&&(a||(a=E("document.location.href",window).substring(0,1200)),b.setup(""),b.sendHandshake("help_panel_main_frame/help_panel_content_frame",""),b.call("help_panel_main_frame/help_panel_content_frame","adaptContext",null,a))};q.close=function(){rc(this.fixedHelpPanelContainer);if(this.onCloseCallback)this.onCloseCallback()};Z.close=function(a,b){rc(b);a&&a()};Z.create=function(a){return new Z(a)};
Z.prototype.close=Z.prototype.close;Z.prototype.updateContext=Z.prototype.updateContext;Z.prototype.openToSmartJourney=Z.prototype.openToSmartJourney;Z.prototype.openToContent=Z.prototype.openToContent;Z.prototype.openToGse=Z.prototype.openToGse;Z.prototype.openHelp=Z.prototype.openHelp;ya("help.api.Lazy.create",function(a){return new Z(a)});ya("help.api.Lazy",Z);}).call(this);
